### ISSUE TITLE
[ER] Authentication fails when connection exceeds SPP Token Lifetime

### ISSUE THREAD

**Issue by aamburn** [OneIdentity/SafeguardDotNet#114]
When a SafeguardConnection is created and persists for longer than the configured Token Lifetime (24 hour default) the using the connection results in an Authentication error from the API.

It would be convenient to provide a persistent connection (similar to the persistent event listener) that will renew the access token automatically.

**Comment by petrsnd** [comment]
SafeguardConnection requires that the caller be aware of access token lifetime and renew their own access token.  @aamburn has provided a PersistentSafeguardConnection class to wrap SafeguardConnection and automatically renew the access token.

See #113

**Comment by petrsnd** [comment]
Published to nuget.org 6.10.0-dev-7714
