### ISSUE TITLE
GuiLogin not working

### ISSUE THREAD

**Issue by ghost** [OneIdentity/SafeguardDotNet#179]
Unable to install and use OneIdentity.SafeguardDotNet.GuiLogin from Nuget package into .NetFramewortk 4.7.2 project because it throws alot of refrence errors

**Comment by Kevin-Andrew** [comment]
We are able to set the `SafeguardDotNetGuiTester` project to the Startup Default:
![image](https://github.com/user-attachments/assets/1104bb3e-929a-4c37-af86-c4de80509e40)
and then run/debug it, passing in the command line parameter for your Safeguard appliance (or just change the code to hard code a value), and we are able to get the login dialog window. Which now uses the Microsoft.Web.WebView2.

Hopefully if you try again with the latest, and/or be sure to clean your solution/environment, it will work for you too. We will close this issue. Thanks.
