### ISSUE TITLE
Username not being passed in BrowserLogin.DefaultBrowserLogin.Connect()

### ISSUE THREAD

**Issue by mattwebb1006** [OneIdentity/SafeguardDotNet#180]
There is a username param, but this username never shows up in the browser.  It looks like it should pass a login_hint url param to autopopulate the username text field, but that parameter never gets passed.

**Comment by Kevin-Andrew** [comment]
This should be addressed in https://www.nuget.org/packages/OneIdentity.SafeguardDotNet/8.0.0-dev-4409 and higher.

Thanks.
