### ISSUE TITLE
Authentication issue via Token / External Federation and Azure on Safeguard API

### ISSUE THREAD

**Issue by S-Lichtenberg** [OneIdentity/SafeguardDotNet#82]
there is no real documentation about how to connect to the Safeguard API and authentication over External Federation (Azure).

![snap](https://user-images.githubusercontent.com/71882339/94265101-3cb57d80-ff38-11ea-939d-06a3a5b51d9d.JPG)

a get token somehow is sadly not very helpful.
A switch in the Connect function from local to External Federation is not working. below the exception

OneIdentity.SafeguardDotNet.SafeguardDotNetException: 'Unable to find scope matching 'External Federation' in [CFF5DF90-27D6-4D5E-96E8-496F543C1522,local]'

Is it broken? if not could you update the Documentation and include authentication via External Federation?

**Comment by petrsnd** [comment]
@S-Lichtenberg Sorry for the delay in responding to this question.  We don't have programmatic support for federated login.  The only option for now is to try to use an interactive login.  This can be done using the SafeguardDotNet.GuiLogin package.  However, that isn't a viable solution depending on your use case.

**Comment by petrsnd** [comment]
@S-Lichtenberg We have additionally added the SafeguardDotNet.BrowserLogin package.

Federated login requires an agent (browser).  You can programmatically manipulate the browser using the SafeguardDotNet.BrowserLogin package.  I am going to close this issue.
