### ISSUE TITLE
Thumbprint Comparison for Certificate Authentication is Case Sensitive

### ISSUE THREAD

**Issue by RichGagliano** [OneIdentity/SafeguardDotNet#83]
The string comparison that matches the user provided thumbprint to the certificate store is currently case sensitive. This should be switched to a case insensitive comparison.

Currently if the thumbprint is lowercase, the following exception will be thrown:

OneIdentity.SafeguardDotNet.SafeguardDotNetException: Failure to get certificate from thumbprint=82f1a5535e098d13cd2356c8678e0c24e8d06b9c ---> OneIdentity.SafeguardDotNet.SafeguardDotNetException: Unable to find certificate matching thumbprint=82f1a5535e098d13cd2356c8678e0c24e8d06b9c in Computer or User store

**Comment by petrsnd** [comment]
Fixed in preview now and in an upcoming release.

**Comment by petrsnd** [comment]
Fix was released in 6.7.1.
